# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Afh2LillSb5_cixj2gwVXb78NQw0z-O
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

#Modelo de trinamento
print("Treinando o Modelo")
iris = load_iris()
X = iris.data  # Características das flores
y = iris.target  # tipos de flores 0, 1 ou 2
nomes_classes = iris.target_names
# variação das plantas e seus nomes setosa, versicolor, virginica

# Treinando o modelo diretamente com o Dataset
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X, y)
print("Modelo treinado com sucesso")

#Fazer o teste com amostra para validar se o codigigo vai funcionar
print("Teste com Amostra Pré-existente ")

amostra_teste = [X[0]]  # seleção dos dados
classe_real = y[0]

previsao = modelo.predict(amostra_teste)[0]

print(f"Dados da amostra escolhida: {amostra_teste[0]}")
print(f"Classe real no dataset: {classe_real} ({nomes_classes[classe_real]})")
print(f"Classe prevista pela IA: {previsao} ({nomes_classes[previsao]})")

if previsao == classe_real:
    print("Resultado: Funcionou.Os resutados batem com o real.")
else:
    print("Resultado: Não funcionou.")

#Menu para o usuario cancelar a adiçãp de uma nova flor
print("Adição de uma nova flor a lista")
print("Digite as medidas da flor que deseja adicionar na classificar.\n digite -1 para sair da adição\n")

while True:
    try:
        # Lendo os valores necessários
        comp_sepala = float(input("Comprimento da sépala : "))
        if comp_sepala == -1: break

        larg_sepala = float(input("Largura da sépala : "))
        if larg_sepala == -1: break

        comp_petala = float(input("Comprimento da pétala : "))
        if comp_petala == -1: break

        larg_petala = float(input("Largura da pétala : "))
        if larg_petala == -1: break

        # Organizando os dados digitados no formato que a IA aceita [[valores]]
        nova_flor = [[comp_sepala, larg_sepala, comp_petala, larg_petala]]

        # Fazendo a classificação
        resultado_id = modelo.predict(nova_flor)[0]
        nome_flor = nomes_classes[resultado_id]

        print(f"\n=> RESULTADO: Essa flor é da espécie: {nome_flor.upper()} (Classe {resultado_id})\n")
        #imprime uma "divisoria feita de "-"
        print("-" * 40)
        #caso o usuario digitar errado o valor
    except ValueError:
        print("Por favor, digite apenas números válidos.")

print("\nProgama finalizado")

#professor desculpa ai mais tem coisas que eu tive que pesquisar na IA tem ate que bastante coisa que me inspirei pra fazer esses code... todos cometarios são meus pare eu intender oq ta acontecendo naquela linha
#print dos vetores

import numpy as np
# Remove as limitações de exibição do print do NumPy(é mutos vetores 0.o)
np.set_printoptions(threshold=np.inf)

print("VETOR X COMPLETO:")
print(X)

print("\nVETOR Y COMPLETO:")
print(y)